version: "3.5"
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: covid19
      POSTGRES_PASSWORD: dsXdsadYsafdDssSpLX
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - 8080:8080

  engine:
    image: codait/max-object-detector
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /tmp:/tmp

  cron:
    image: cron:1
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: covid19
      POSTGRES_PASSWORD: dsXdsadYsafdDssSpLX
      POSTGRES_DB: postgres
    ports:
      - 5001:5000
    volumes:
      - /tmp:/tmp
    depends_on:
      - "db"

  api:
    image: api:1
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: covid19
      POSTGRES_PASSWORD: dsXdsadYsafdDssSpLX
      POSTGRES_DB: postgres
    ports:
      - 5002:5000
    volumes:
      - /tmp:/tmp
    depends_on:
      - "db"

  ui:
    image: ui-rignano:prod
    ports:
      - 80:80